CREATE TABLE cfb (team TEXT, tid TEXT PRIMARY KEY, conf TEXT);
insert into cfb (team, tid, conf) VALUES ('Boston College','BC','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Clemson','CLEM','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Florida State','FSU','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Maryland','MD','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('North Carolina State','NCST','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Wake Forest','WAKE','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Duke','DUKE','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Georgia Tech','GATECH','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Miami (Fla.)','MIAMI','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('North Carolina','UNC','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Virginia','UVA','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Virginia Tech','VATECH','Atlantic Coast');
insert into cfb (team, tid, conf) VALUES ('Baylor','BAYLOR','Big 12');
insert into cfb (team, tid, conf) VALUES ('Iowa State','IOWAST','Big 12');
insert into cfb (team, tid, conf) VALUES ('Kansas','KANSAS','Big 12');
insert into cfb (team, tid, conf) VALUES ('Kansas State','KSTATE','Big 12');
insert into cfb (team, tid, conf) VALUES ('Oklahoma','OKLA','Big 12');
insert into cfb (team, tid, conf) VALUES ('Oklahoma State','OKLAST','Big 12');
insert into cfb (team, tid, conf) VALUES ('TCU','TCU','Big 12');
insert into cfb (team, tid, conf) VALUES ('Texas','TEXAS','Big 12');
insert into cfb (team, tid, conf) VALUES ('Texas Tech','TXTECH','Big 12');
insert into cfb (team, tid, conf) VALUES ('West Virginia','WVU','Big 12');
insert into cfb (team, tid, conf) VALUES ('Cincinnati','CINCY','Big East');
insert into cfb (team, tid, conf) VALUES ('Connecticut','UCONN','Big East');
insert into cfb (team, tid, conf) VALUES ('Louisville','LVILLE','Big East');
insert into cfb (team, tid, conf) VALUES ('Pittsburgh','PITT','Big East');
insert into cfb (team, tid, conf) VALUES ('Rutgers','RUT','Big East');
insert into cfb (team, tid, conf) VALUES ('South Florida','SFLA','Big East');
insert into cfb (team, tid, conf) VALUES ('Syracuse','CUSE','Big East');
insert into cfb (team, tid, conf) VALUES ('Temple','TEMPLE','Big East');
insert into cfb (team, tid, conf) VALUES ('Iowa','IOWA','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Michigan','MICH','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Michigan State','MICHST','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Minnesota','MINN','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Nebraska','NEB','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Northwestern','NWEST','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Illinois','ILL','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Indiana','IND','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Ohio State','OHIOST','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Penn State','PSU','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Purdue','PURDUE','Big Ten');
insert into cfb (team, tid, conf) VALUES ('Wisconsin','WISC','Big Ten');
insert into cfb (team, tid, conf) VALUES ('East Carolina','ECU','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Memphis','MEMP','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Marshall','MRSHL','Conference USA');
insert into cfb (team, tid, conf) VALUES ('UAB','UAB','Conference USA');
insert into cfb (team, tid, conf) VALUES ('UCF','UCF','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Southern Mississippi','USM','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Houston','HOU','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Rice','RICE','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Southern Methodist','SMU','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Tulane','TULANE','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Tulsa','TULSA','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Texas-El Paso','UTEP','Conference USA');
insert into cfb (team, tid, conf) VALUES ('Army','ARMY','FBS Independents');
insert into cfb (team, tid, conf) VALUES ('Brigham Young','BYU','FBS Independents');
insert into cfb (team, tid, conf) VALUES ('Georgia State','GAST','FBS Independents');
insert into cfb (team, tid, conf) VALUES ('Navy','NAVY','FBS Independents');
insert into cfb (team, tid, conf) VALUES ('Notre Dame','ND','FBS Independents');
insert into cfb (team, tid, conf) VALUES ('Akron','AKRON','Mid American');
insert into cfb (team, tid, conf) VALUES ('Bowling Green','BGREEN','Mid American');
insert into cfb (team, tid, conf) VALUES ('Buffalo','BUFF','Mid American');
insert into cfb (team, tid, conf) VALUES ('Kent State','KENTST','Mid American');
insert into cfb (team, tid, conf) VALUES ('Massachusetts','MA','Mid American');
insert into cfb (team, tid, conf) VALUES ('Miami (Ohio)','MIAOH','Mid American');
insert into cfb (team, tid, conf) VALUES ('Ohio','OHIO','Mid American');
insert into cfb (team, tid, conf) VALUES ('Ball State','BALLST','Mid American');
insert into cfb (team, tid, conf) VALUES ('Central Michigan','CMICH','Mid American');
insert into cfb (team, tid, conf) VALUES ('Eastern Michigan','EMICH','Mid American');
insert into cfb (team, tid, conf) VALUES ('Northern Illinois','NILL','Mid American');
insert into cfb (team, tid, conf) VALUES ('Toledo','TOLEDO','Mid American');
insert into cfb (team, tid, conf) VALUES ('Western Michigan','WMICH','Mid American');
insert into cfb (team, tid, conf) VALUES ('Air Force','AF','Mountain West');
insert into cfb (team, tid, conf) VALUES ('Boise State','BOISE','Mountain West');
insert into cfb (team, tid, conf) VALUES ('Colorado State','COLOST','Mountain West');
insert into cfb (team, tid, conf) VALUES ('Fresno State','FRESNO','Mountain West');
insert into cfb (team, tid, conf) VALUES ('Hawaii','HAWAII','Mountain West');
insert into cfb (team, tid, conf) VALUES ('Nevada','NEVADA','Mountain West');
insert into cfb (team, tid, conf) VALUES ('New Mexico','NMEX','Mountain West');
insert into cfb (team, tid, conf) VALUES ('San Diego State','SDGST','Mountain West');
insert into cfb (team, tid, conf) VALUES ('UNLV','UNLV','Mountain West');
insert into cfb (team, tid, conf) VALUES ('Wyoming','WYO','Mountain West');
insert into cfb (team, tid, conf) VALUES ('California','CAL','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Oregon','OREG','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Oregon State','OREGST','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Stanford','STNFRD','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Washington','WASH','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Washington State','WASHST','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Arizona','ARIZ','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Arizona State','ARIZST','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Colorado','COLO','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('UCLA','UCLA','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Southern California','USC','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Utah','UTAH','Pacific 12');
insert into cfb (team, tid, conf) VALUES ('Florida','FLA','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Georgia','UGA','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Kentucky','UK','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Missouri','MIZZOU','Southeastern');
insert into cfb (team, tid, conf) VALUES ('South Carolina','SC','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Tennessee','TENN','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Vanderbilt','VANDY','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Alabama','BAMA','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Arkansas','ARK','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Auburn','AUBURN','Southeastern');
insert into cfb (team, tid, conf) VALUES ('LSU','LSU','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Mississippi','MISS','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Mississippi State','MISSST','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Texas A&M;','TXAM','Southeastern');
insert into cfb (team, tid, conf) VALUES ('Arkansas State','ARKST','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('Florida Atlantic','FAU','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('Florida International','FIU','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('La.-Lafayette','LALAF','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('Louisiana-Monroe','LAMON','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('Middle Tennessee','MTSU','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('North Texas','NTEXAS','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('South Alabama','SALA','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('Troy','TROY','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('Western Kentucky','WKY','Sun Belt');
insert into cfb (team, tid, conf) VALUES ('Idaho','IDAHO','Western Athletic');
insert into cfb (team, tid, conf) VALUES ('Louisiana Tech','LATECH','Western Athletic');
insert into cfb (team, tid, conf) VALUES ('New Mexico State','NMEXST','Western Athletic');
insert into cfb (team, tid, conf) VALUES ('San Jose State','SJST','Western Athletic');
insert into cfb (team, tid, conf) VALUES ('Texas State-San Marcos','TXSTSM','Western Athletic');
insert into cfb (team, tid, conf) VALUES ('Texas-San Antonio','TXSA','Western Athletic');
insert into cfb (team, tid, conf) VALUES ('Utah State','UTAHST','Western Athletic');

CREATE TABLE confs (full TEXT, short TEXT);
insert into confs (full, short) VALUES ('Big Ten','BIG10');
insert into confs (full, short) VALUES ('Atlantic Coast','ACC');
insert into confs (full, short) VALUES ('Big East','BIGE');
insert into confs (full, short) VALUES ('Pacific 12','PAC12'); 
insert into confs (full, short) VALUES ('Big 12','BIG12');
insert into confs (full, short) VALUES ('Conference USA','USA');
insert into confs (full, short) VALUES ('Mid American','MAC');
insert into confs (full, short) VALUES ('FBS Independents','IA');
insert into confs (full, short) VALUES ('Mountain West','MWC');
insert into confs (full, short) VALUES ('Southeastern','SEC');
insert into confs (full, short) VALUES ('Sun Belt','SUN');
insert into confs (full, short) VALUES ('Western Athletic','WAC');
