CREATE TABLE cfb (team TEXT,tid TEXT PRIMARY KEY,conf TEXT,nn TEXT,eid INTEGER,usat INTEGER, cfbstats INTEGER);
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('boston college','BC','atlantic coast','eagles','103','34','67');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('clemson','CLEM','atlantic coast','tigers','228','128','147');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('florida state','FSU','atlantic coast','seminoles','52','47','234');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('maryland','MD','atlantic coast','terrapins','120','60','392');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('north carolina state','NCST','atlantic coast','wolfpack','152','79','490');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('wake forest','WAKE','atlantic coast','demon deacons','154','138','749');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('duke','DUKE','atlantic coast','blue devils','150','95','193');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('georgia tech','GATECH','atlantic coast','yellow jackets','59','125','255');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('miami','MIAMI','atlantic coast','hurricanes','2390','70','415');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('north carolina','UNC','atlantic coast','tar heels','153','65','457');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('virginia','UVA','atlantic coast','cavaliers','258','134','746');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('virginia tech','VATECH','atlantic coast','hokies','259','45','742');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('baylor','BAYLOR','big 12','bears','239','88','51');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('iowa state','IOWAST','big 12','cyclones','66','101','311');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('kansas','KANSAS','big 12','jayhawks','2305','49','328');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('kansas state','KSTATE','big 12','wildcats','2306','130','327');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('oklahoma','OKLA','big 12','sooners','201','139','522');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('oklahoma state','OKLAST','big 12','cowboys','197','53','521');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('tcu','TCU','big 12','horned frogs','2628','110','698');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('texas','TEXAS','big 12','longhorns','251','131','703');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('texas tech','TXTECH','big 12','red raiders','2641','64','700');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('west virginia','WVU','big 12','mountaineers','277','62','768');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('cincinnati','CINCY','big east','bearcats','2132','46','140');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('connecticut','UCONN','big east','huskies','41','144','164');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('louisville','LVILLE','big east','cardinals','97','61','367');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('pittsburgh','PITT','big east','panthers','221','36','545');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('rutgers','RUT','big east','scarlet knights','164','129','587');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('south florida','SFLA','big east','bulls','58','204','651');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('syracuse','CUSE','big east','orange','183','104','688');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('temple','TEMPLE','big east','owls','218','56','690');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('iowa','IOWA','big ten','hawkeyes','2294','133','312');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('michigan','MICH','big ten','wolverines','130','103','418');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('michigan state','MICHST','big ten','spartans','127','113','416');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('minnesota','MINN','big ten','golden gophers','135','140','428');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('nebraska','NEB','big ten','cornhuskers','158','55','463');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('northwestern','NWEST','big ten','wildcats','77','94','509');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('illinois','ILL','big ten','fighting illini','356','72','301');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('indiana','IND','big ten','hoosiers','84','107','306');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('ohio state','OHIOST','big ten','buckeyes','194','105','518');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('penn state','PSU','big ten','nittany lions','213','59','539');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('purdue','PURDUE','big ten','boilermakers','2509','35','559');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('wisconsin','WISC','big ten','badgers','275','111','796');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('east carolina','ECU','conference usa','pirates','151','78','196');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('memphis','MEMP','conference usa','tigers','235','37','404');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('marshall','MRSHL','conference usa','thundering herd','276','118','388');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('uab','UAB','conference usa','blazers','5','146','9');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('ucf','UCF','conference usa','knights','2116','142','128');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('southern mississippi','USM','conference usa','golden eagles','2572','58','664');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('houston','HOU','conference usa','cougars','248','96','288');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('rice','RICE','conference usa','owls','242','98','574');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('southern methodist','SMU','conference usa','mustangs','2567','73','663');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('tulane','TULANE','conference usa','green wave','2655','48','718');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('tulsa','TULSA','conference usa','golden hurricane','202','97','719');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('texas-el paso','UTEP','conference usa','miners','2638','41','704');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('army','ARMY','fbs independents','black knights','349','127','725');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('brigham young','BYU','fbs independents','cougars','252','33','77');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('navy','NAVY','fbs independents','midshipmen','2426','66','726');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('notre dame','ND','fbs independents','fighting irish','87','102','513');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('akron','AKRON','mid american','zips','2006','124','5');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('bowling green','BGREEN','mid american','green falcons','189','85','71');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('buffalo','BUFF','mid american','bulls','2084','145','86');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('kent state','KENTST','mid american','golden flashes','2309','123','331');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('massachusetts','MA','mid american','minutemen','113','207','400');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('miami (ohio)','MIAOH','mid american','redhawks','193','121','414');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('ohio','OHIO','mid american','bobcats','195','117','519');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('ball state','BALLST','mid american','cardinals','2050','86','47');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('central michigan','CMICH','mid american','chippewas','2117','141','129');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('eastern michigan','EMICH','mid american','eagles','2199','136','204');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('northern illinois','NILL','mid american','huskies','2459','68','503');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('toledo','TOLEDO','mid american','rockets','2649','82','709');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('western michigan','WMICH','mid american','broncos','2711','67','774');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('air force','AF','mountain west','falcons','2005','42','721');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('boise state','BOISE','mountain west','broncos','68','92','66');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('colorado state','COLOST','mountain west','rams','36','89','156');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('fresno state','FRESNO','mountain west','bulldogs','278','109','96');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('hawaii','HAWAII','mountain west','warriors','62','50','277');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('nevada','NEVADA','mountain west','wolf pack','2440','135','466');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('new mexico','NMEX','mountain west','lobos','167','63','473');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('san diego state','SDGST','mountain west','aztecs','21','132','626');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('unlv','UNLV','mountain west','rebels','2439','108','465');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('wyoming','WYO','mountain west','cowboys','2751','87','811');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('california','CAL','pacific 12','golden bears','25','44','107');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('oregon','OREG','pacific 12','ducks','2483','39','529');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('oregon state','OREGST','pacific 12','beavers','204','81','528');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('stanford','STNFRD','pacific 12','cardinal','24','106','674');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('washington','WASH','pacific 12','huskies','264','54','756');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('washington state','WASHST','pacific 12','cougars','265','40','754');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('arizona','ARIZ','pacific 12','wildcats','12','83','29');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('arizona state','ARIZST','pacific 12','sun devils','9','112','28');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('colorado','COLO','pacific 12','buffalos','38','90','157');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('ucla','UCLA','pacific 12','bruins','26','91','110');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('southern california','USC','pacific 12','trojans','30','71','657');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('utah','UTAH','pacific 12','utes','254','93','732');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('florida','FLA','southeastern','gators','57','69','235');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('georgia','UGA','southeastern','bulldogs','61','52','257');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('kentucky','UK','southeastern','wildcats','96','122','334');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('missouri','MIZZOU','southeastern','tigers','142','119','434');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('south carolina','SC','southeastern','gamecocks','2579','161','648');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('tennessee','TENN','southeastern','volunteers','2633','114','694');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('vanderbilt','VANDY','southeastern','commodores','238','115','736');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('alabama','BAMA','southeastern','crimson tide','333','51','8');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('arkansas','ARK','southeastern','razorbacks','8','126','31');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('auburn','AUBURN','southeastern','tigers','2','84','37');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('lsu','LSU','southeastern','tigers','99','116','365');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('mississippi','MISS','southeastern','rebels','145','77','433');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('mississippi state','MISSST','southeastern','bulldogs','344','76','430');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('texas a&m','TXAM','southeastern','aggies','245','120','697');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('arkansas state','ARKST','sun belt','red wolves','2032','75','30');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('florida atlantic','FAU','sun belt','owls','2226','221','229');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('florida international','FIU','sun belt','golden panthers','2229','230','231');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('la.-lafayette','LALAF','sun belt','ragin cajuns','309','38','671');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('louisiana-monroe','LAMON','sun belt','warhawks','2433','137','498');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('middle tennessee','MTSU','sun belt','blue raiders','2393','143','419');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('north texas','NTEXAS','sun belt','mean green','249','99','497');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('south alabama','SALA','sun belt','jaguars','6','459','646');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('troy','TROY','sun belt','trojans','2653','196','716');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('western kentucky','WKY','sun belt','hilltoppers','98','189','772');

insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('idaho','IDAHO','western athletic','vandals','70','80','295');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('louisiana tech','LATECH','western athletic','bulldogs','2348','57','366');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('new mexico state','NMEXST','western athletic','aggies','166','74','472');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('san jose state','SJST','western athletic','spartans','23','43','630');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('texas state','TXSTSM','western athletic','bobcats','326','233','670');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('utah state','UTAHST','western athletic','aggies','328','100','731');
insert into cfb (team,tid,conf,nn,eid,usat,cfbstats) VALUES ('texas-san antonio','TXSA','western athletic','roadrunners','2636','461','706');

CREATE TABLE confs (full TEXT, short TEXT, eid INTEGER);
insert into confs (full, short, eid) VALUES ('big ten','BIG10','5');
insert into confs (full, short, eid) VALUES ('atlantic coast','ACC','1');
insert into confs (full, short, eid) VALUES ('big east','BIGE','10');
insert into confs (full, short, eid) VALUES ('pacific 12','PAC12','9'); 
insert into confs (full, short, eid) VALUES ('big 12','BIG12','4');
insert into confs (full, short, eid) VALUES ('conference usa','USA','12');
insert into confs (full, short, eid) VALUES ('mid american','MAC','15');
insert into confs (full, short, eid) VALUES ('fbs independents','IA','18');
insert into confs (full, short, eid) VALUES ('mountain west','MWC','17');
insert into confs (full, short, eid) VALUES ('southeastern','SEC','8');
insert into confs (full, short, eid) VALUES ('sun belt','SUN','37');
insert into confs (full, short, eid) VALUES ('western athletic','WAC','16');
